backend:
  # https://decapcms.org/docs/github-backend/
  name: github
  branch: main # Branch to update (optional; defaults to master)
  # https://decapcms.org/docs/github-backend/
  repo: alexanderankin/gh-pages-test

publish_mode: editorial_workflow
media_folder: src/images/uploads
public_folder: /gh-pages-test/images/uploads
collections:
  - name: posts
    label: Post
    folder: _posts/posts
    create: true
    #slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string, default: Post }
      - { label: Content, name: content, widget: markdown, default: '# Hello' }
#
